displayName: JWT2Headers converter middleware
type: middleware

import: github.com/Farrukhraz/jwt2headers

summary: 'Extract some JWT values and append them to headers'

testData:
  Cookies:
    jwt_token: "your_cookie"
  redirectUrl: "https://google.com"
  contourSeparator:
    - separator:
        domain: prod.fake.com
        allowedGroup: PROD
    - separator:
        domain: dev.fake.com
        allowedGroup: DEV
    - separator:
        domain: test.fake.com
        allowedGroup: TEST
